quarkus:
  smallrye-openapi.path: /swagger
  swagger-ui.always-include: true
  kubernetes-client:
    trust-certs: true
  kubernetes-config:
    enabled: true
    config-maps:
      - orders-config
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: load.sql
  datasource:
    db-kind: postgresql
    username: connect23
    password: connect23
    jdbc:
      url: jdbc:postgresql://localhost:5432/ordermgmt-db

  log:
    level: DEBUG
    category:
      "io.ordermanagement.order":
        level: DEBUG
  jaeger:
    endpoint: http://localhost:14268/api/traces
    sampler-type: const
    sampler-param: 1

  # container-image:
  #   build: true
  #   registry: quay.io
  #   group: openshiftlabs
  #   name: app-mod-inventory
  #   tag: 1.0

"%dev":
  quarkus:
    http:
      port: 8084
    kubernetes-config:
      enabled: false
    datasource:
      # db-kind: h2
      # jdbc:
      #   url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: connect23
      password: connect23
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/ordermgmt-db


"%test":
  quarkus:
    kubernetes-config:
      enabled: false
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
